In [3]:
import numpy as np
import pandas as pd

# Load the exoplanet dataset
df = pd.read_csv("exoplanet_analytics_dataset.csv")

print("NumPy version:", np.__version__)
print("Pandas version:", pd.__version__)

print("\nDataset loaded successfully!")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

NumPy version: 2.5.4
Pandas version: 3.0.6

Dataset loaded successfully!
Rows: 75
Columns: 8

In [4]:
df.head()

,Planet,Observation_Date,Normalized_Brightness,Transit_Detected,Transit_Depth,Orbital_Period_Days,Transit_Duration_Hours,Observation_Quality
0,Kepler-10 b,2025-01-01,0.998599,Yes,0.0015,0.8375,2.2,Excellent
1,Kepler-10 b,2025-01-01,0.999972,No,0.0000,0.8375,2.2,Fair
2,Kepler-10 b,2025-01-01,0.999778,No,0.0000,0.8375,2.2,Excellent
3,Kepler-10 b,2025-01-01,0.998564,Yes,0.0015,0.8375,2.2,Excellent
4,Kepler-10 b,2025-01-02,1.000316,No,0.0000,0.8375,2.2,Good

In [5]:
df.tail()

,Planet,Observation_Date,Normalized_Brightness,Transit_Detected,Transit_Depth,Orbital_Period_Days,Transit_Duration_Hours,Observation_Quality
70,Kepler-452 b,2028-07-06,1.000255,No,0.0000,384.8,10.0,Good
71,Kepler-452 b,2028-11-11,0.999942,No,0.0000,384.8,10.0,Excellent
72,Kepler-452 b,2029-03-20,0.999401,Yes,0.0006,384.8,10.0,Good
73,Kepler-452 b,2029-07-26,0.999953,No,0.0000,384.8,10.0,Good
74,Kepler-452 b,2029-12-01,0.999921,No,0.0000,384.8,10.0,Fair

In [6]:
# Create a 1D NumPy array
brightness = np.array(df["Normalized_Brightness"])

print("1D Array:")
print(brightness[:10])

# Create a 2D NumPy array
numerical_data = np.array(
    df[
        [
            "Normalized_Brightness",
            "Transit_Depth",
            "Orbital_Period_Days",
            "Transit_Duration_Hours"
        ]
    ]
)

print("\n2D Array:")
print(numerical_data[:5])

print("\nShape of 1D array:", brightness.shape)
print("Shape of 2D array:", numerical_data.shape)

1D Array:
[0.998599 0.999972 0.999778 0.998564 1.000316 1.000153 0.998384 0.999895
 1.000048 0.998117]

2D Array:
[[9.985990e-01 1.500000e-03 8.375000e-01 2.200000e+00]
 [9.999720e-01 0.000000e+00 8.375000e-01 2.200000e+00]
 [9.997780e-01 0.000000e+00 8.375000e-01 2.200000e+00]
 [9.985640e-01 1.500000e-03 8.375000e-01 2.200000e+00]
 [1.000316e+00 0.000000e+00 8.375000e-01 2.200000e+00]]

Shape of 1D array: (75,)
Shape of 2D array: (75, 4)

In [7]:
# Take first 10 brightness values
a = brightness[:10]

# Create another array
b = np.ones(10)

print("Array A:")
print(a)

print("\nArray B:")
print(b)

print("\nAddition:")
print(a + b)

print("\nSubtraction:")
print(a - b)

print("\nMultiplication:")
print(a * b)

print("\nDivision:")
print(a / b)

print("\nTotal:", np.sum(a))
print("Average:", np.mean(a))
print("Minimum:", np.min(a))
print("Maximum:", np.max(a))

Array A:
[0.998599 0.999972 0.999778 0.998564 1.000316 1.000153 0.998384 0.999895
 1.000048 0.998117]

Array B:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

Addition:
[1.998599 1.999972 1.999778 1.998564 2.000316 2.000153 1.998384 1.999895
 2.000048 1.998117]

Subtraction:
[-1.401e-03 -2.800e-05 -2.220e-04 -1.436e-03  3.160e-04  1.530e-04
 -1.616e-03 -1.050e-04  4.800e-05 -1.883e-03]

Multiplication:
[0.998599 0.999972 0.999778 0.998564 1.000316 1.000153 0.998384 0.999895
 1.000048 0.998117]

Division:
[0.998599 0.999972 0.999778 0.998564 1.000316 1.000153 0.998384 0.999895
 1.000048 0.998117]

Total: 9.993826
Average: 0.9993826
Minimum: 0.998117
Maximum: 1.000316

In [8]:
brightness_change = brightness - 1.0

print("First 10 brightness values:")
print(brightness[:10])

print("\nBrightness change from normal level:")
print(brightness_change[:10])

First 10 brightness values:
[0.998599 0.999972 0.999778 0.998564 1.000316 1.000153 0.998384 0.999895
 1.000048 0.998117]

Brightness change from normal level:
[-1.401e-03 -2.800e-05 -2.220e-04 -1.436e-03  3.160e-04  1.530e-04
 -1.616e-03 -1.050e-04  4.800e-05 -1.883e-03]

In [ ]:
#Series from a list
planet_series = pd.Series(
    ["Kepler-10 b", "Kepler-11 b", "Kepler-22 b", "Kepler-452 b"]
)

print(planet_series)

0     Kepler-10 b
1     Kepler-11 b
2     Kepler-22 b
3    Kepler-452 b
dtype: str

In [10]:
brightness_series = df["Normalized_Brightness"]

print(brightness_series.head())

0    0.998599
1    0.999972
2    0.999778
3    0.998564
4    1.000316
Name: Normalized_Brightness, dtype: float64

In [11]:
print("Sum:", brightness_series.sum())
print("Mean:", brightness_series.mean())
print("Minimum:", brightness_series.min())
print("Maximum:", brightness_series.max())
print("Median:", brightness_series.median())
print("Standard Deviation:", brightness_series.std())

Sum: 74.95287000000002
Mean: 0.9993716000000002
Minimum: 0.99385
Maximum: 1.000695
Median: 0.99986
Standard Deviation: 0.0014766374237032834

In [12]:
print("First value:")
print(brightness_series.iloc[0])

print("\nFirst 5 values:")
print(brightness_series.iloc[:5])

print("\nValues from index 10 to 15:")
print(brightness_series.iloc[10:16])

First value:
0.998599

First 5 values:
0    0.998599
1    0.999972
2    0.999778
3    0.998564
4    1.000316
Name: Normalized_Brightness, dtype: float64

Values from index 10 to 15:
10    1.000163
11    0.999695
12    0.998318
13    0.999718
14    0.999874
15    0.994149
Name: Normalized_Brightness, dtype: float64

In [13]:
low_brightness = brightness_series[brightness_series < 0.99]

print(low_brightness)

Series([], Name: Normalized_Brightness, dtype: float64)

In [14]:
print("Shape:")
print(df.shape)

print("\nColumns:")
print(df.columns)

print("\nData Types:")
print(df.dtypes)

Shape:
(75, 8)

Columns:
Index(['Planet', 'Observation_Date', 'Normalized_Brightness',
       'Transit_Detected', 'Transit_Depth', 'Orbital_Period_Days',
       'Transit_Duration_Hours', 'Observation_Quality'],
      dtype='str')

Data Types:
Planet                        str
Observation_Date              str
Normalized_Brightness     float64
Transit_Detected              str
Transit_Depth             float64
Orbital_Period_Days       float64
Transit_Duration_Hours    float64
Observation_Quality           str
dtype: object

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 75 entries, 0 to 74
Data columns (total 8 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Planet                  75 non-null     str
 1   Observation_Date        75 non-null     str
 2   Normalized_Brightness   75 non-null     float64
 3   Transit_Detected        75 non-null     str
 4   Transit_Depth           75 non-null     float64
 5   Orbital_Period_Days     75 non-null     float64
 6   Transit_Duration_Hours  75 non-null     float64
 7   Observation_Quality     75 non-null     str
dtypes: float64(4), str(4)
memory usage: 7.0 KB

In [16]:
df.describe()

,Normalized_Brightness,Transit_Depth,Orbital_Period_Days,Transit_Duration_Hours
count,75.000000,75.000000,75.00000,75.000000
mean,0.999372,0.000627,161.82672,5.020000
std,0.001477,0.001506,154.69804,3.146684
min,0.993850,0.000000,0.83750,2.200000
25%,0.999380,0.000000,3.69610,2.500000
50%,0.999860,0.000000,129.90000,3.000000
75%,1.000046,0.000600,289.90000,7.400000
max,1.000695,0.006000,384.80000,10.000000

In [17]:
print("Planets:")
print(df["Planet"].unique())

print("\nTransit Detection:")
print(df["Transit_Detected"].unique())

print("\nObservation Quality:")
print(df["Observation_Quality"].unique())

Planets:
<ArrowStringArray>
['Kepler-10 b', 'Kepler-20 b', 'Kepler-22 b', 'Kepler-186 f', 'Kepler-452 b']
Length: 5, dtype: str

Transit Detection:
<ArrowStringArray>
['Yes', 'No']
Length: 2, dtype: str

Observation Quality:
<ArrowStringArray>
['Excellent', 'Fair', 'Good']
Length: 3, dtype: str

In [18]:
numeric_columns = [
    "Normalized_Brightness",
    "Transit_Depth",
    "Orbital_Period_Days",
    "Transit_Duration_Hours"
]

for column in numeric_columns:
    print("\n", column)
    print("Total:", df[column].sum())
    print("Average:", df[column].mean())
    print("Minimum:", df[column].min())
    print("Maximum:", df[column].max())

 Normalized_Brightness
Total: 74.95287000000002
Average: 0.9993716000000002
Minimum: 0.99385
Maximum: 1.000695

 Transit_Depth
Total: 0.047
Average: 0.0006266666666666666
Minimum: 0.0
Maximum: 0.006

 Orbital_Period_Days
Total: 12137.003999999997
Average: 161.82671999999997
Minimum: 0.8375
Maximum: 384.8

 Transit_Duration_Hours
Total: 376.5
Average: 5.02
Minimum: 2.2
Maximum: 10.0

In [19]:
brightness_np = np.array(df["Normalized_Brightness"])

numpy_mean = np.mean(brightness_np)
pandas_mean = df["Normalized_Brightness"].mean()

numpy_total = np.sum(brightness_np)
pandas_total = df["Normalized_Brightness"].sum()

print("NumPy Mean:", numpy_mean)
print("Pandas Mean:", pandas_mean)

print("\nNumPy Total:", numpy_total)
print("Pandas Total:", pandas_total)

print("\nMean values equal:", np.isclose(numpy_mean, pandas_mean))
print("Total values equal:", np.isclose(numpy_total, pandas_total))

NumPy Mean: 0.9993716000000002
Pandas Mean: 0.9993716000000002

NumPy Total: 74.95287000000002
Pandas Total: 74.95287000000002

Mean values equal: True
Total values equal: True

In [20]:
df["Observation_Date"] = pd.to_datetime(df["Observation_Date"])

print(df["Observation_Date"].dtype)
print(df.head())

datetime64[us]
        Planet Observation_Date  Normalized_Brightness Transit_Detected  \
0  Kepler-10 b       2025-01-01               0.998599              Yes
1  Kepler-10 b       2025-01-01               0.999972               No
2  Kepler-10 b       2025-01-01               0.999778               No
3  Kepler-10 b       2025-01-01               0.998564              Yes
4  Kepler-10 b       2025-01-02               1.000316               No

   Transit_Depth  Orbital_Period_Days  Transit_Duration_Hours  \
0         0.0015               0.8375                     2.2
1         0.0000               0.8375                     2.2
2         0.0000               0.8375                     2.2
3         0.0015               0.8375                     2.2
4         0.0000               0.8375                     2.2

  Observation_Quality
0           Excellent
1                Fair
2           Excellent
3           Excellent
4                Good

In [21]:
daily_summary = df.groupby("Observation_Date").agg(
    Observation_Count=("Planet", "count"),
    Average_Brightness=("Normalized_Brightness", "mean"),
    Average_Transit_Depth=("Transit_Depth", "mean")
)

daily_summary

                  Observation_Count  Average_Brightness  Average_Transit_Depth
Observation_Date
2025-01-01                        8            0.998569               0.001362
2025-01-02                        5            0.999722               0.000300
2025-01-03                        4            0.999589               0.000375
2025-01-04                        5            0.998291               0.001500
2025-01-05                        1            1.000237               0.000000
2025-01-07                        1            0.999850               0.000000
2025-01-08                        1            0.994463               0.006000
2025-01-09                        1            0.999867               0.000000
2025-01-10                        1            0.999999               0.000000
2025-01-12                        1            0.994206               0.006000
2025-01-13                        1            0.999695               0.000000
2025-01-14                        1            1.000695               0.000000
2025-01-15                        1            0.994298               0.006000
2025-01-17                        1            1.000185               0.000000
2025-01-18                        1            1.000043               0.000000
2025-02-13                        1            1.000184               0.000000
2025-03-28                        1            1.000065               0.000000
2025-04-07                        1            0.999715               0.000000
2025-05-09                        1            0.999900               0.000000
2025-05-10                        1            0.999380               0.000700
2025-06-23                        1            0.999858               0.000000
2025-07-13                        1            0.999917               0.000000
2025-08-05                        1            1.000329               0.000000
2025-09-14                        1            1.000100               0.000000
2025-09-17                        1            0.999374               0.000700
2025-10-17                        1            0.999590               0.000600
2025-10-31                        1            0.999424               0.000000
2025-12-13                        1            1.000181               0.000000
2026-01-20                        1            0.999632               0.000600
2026-01-22                        1            0.999797               0.000000
2026-01-25                        1            0.998988               0.000700
2026-03-10                        1            1.000229               0.000000
2026-04-22                        1            0.999952               0.000000
2026-04-29                        1            1.000024               0.000000
2026-05-29                        1            0.999894               0.000000
2026-06-04                        1            0.999379               0.000700
2026-07-17                        1            0.999826               0.000000
2026-08-03                        1            0.999278               0.000600
2026-08-30                        1            1.000164               0.000000
2026-10-04                        1            1.000103               0.000000
2026-11-08                        1            1.000110               0.000000
2027-02-09                        1            0.999674               0.000600
2027-02-13                        1            1.000105               0.000000
2027-05-20                        1            0.999560               0.000600
2027-06-17                        1            1.000035               0.000000
2027-08-25                        1            0.999849               0.000000
2027-10-24                        1            0.999860               0.000000
2027-11-29                        1            0.999944               0.000000
2028-02-29                        1            0.999334               0.000600
2028-03-05                        1            0.999129               0.000600
2028-06-10                        1            1.000198               0.000000
2028-07-06                        1            1.000255               0.000000
2028-09-14                        1            0.999801               0.000000
2028-11-11                        1            0.999942               0.000000
2029-03-20                        1            0.999401               0.000600
2029-07-26                        1            0.999953               0.000000
2029-12-01                        1            0.999921               0.000000

In [22]:
print("Missing values in each column:")
print(df.isnull().sum())

Missing values in each column:
Planet                    0
Observation_Date          0
Normalized_Brightness     0
Transit_Detected          0
Transit_Depth             0
Orbital_Period_Days       0
Transit_Duration_Hours    0
Observation_Quality       0
dtype: int64

In [23]:
print("Number of duplicate rows:")
print(df.duplicated().sum())

Number of duplicate rows:
0

In [24]:
df_clean = df.drop_duplicates().copy()

print("Original rows:", len(df))
print("Rows after removing duplicates:", len(df_clean))
print("Duplicates remaining:", df_clean.duplicated().sum())

Original rows: 75
Rows after removing duplicates: 75
Duplicates remaining: 0

In [25]:
df_clean["Brightness_Drop"] = 1 - df_clean["Normalized_Brightness"]

df_clean[
    [
        "Planet",
        "Normalized_Brightness",
        "Brightness_Drop"
    ]
].head(10)

        Planet  Normalized_Brightness  Brightness_Drop
0  Kepler-10 b               0.998599         0.001401
1  Kepler-10 b               0.999972         0.000028
2  Kepler-10 b               0.999778         0.000222
3  Kepler-10 b               0.998564         0.001436
4  Kepler-10 b               1.000316        -0.000316
5  Kepler-10 b               1.000153        -0.000153
6  Kepler-10 b               0.998384         0.001616
7  Kepler-10 b               0.999895         0.000105
8  Kepler-10 b               1.000048        -0.000048
9  Kepler-10 b               0.998117         0.001883

In [27]:
print("Brightness Drop")
print("Average:", df_clean["Brightness_Drop"].mean())
print("Minimum:", df_clean["Brightness_Drop"].min())
print("Maximum:", df_clean["Brightness_Drop"].max())

Brightness Drop
Average: 0.0006284000000000045
Minimum: -0.0006949999999998902
Maximum: 0.006149999999999989

In [28]:
kepler_10 = df_clean[df_clean["Planet"] == "Kepler-10 b"]

kepler_10

,Planet,Observation_Date,Normalized_Brightness,Transit_Detected,Transit_Depth,Orbital_Period_Days,Transit_Duration_Hours,Observation_Quality,Brightness_Drop
0,Kepler-10 b,2025-01-01,0.998599,Yes,0.0015,0.8375,2.2,Excellent,0.001401
1,Kepler-10 b,2025-01-01,0.999972,No,0.0000,0.8375,2.2,Fair,0.000028
2,Kepler-10 b,2025-01-01,0.999778,No,0.0000,0.8375,2.2,Excellent,0.000222
3,Kepler-10 b,2025-01-01,0.998564,Yes,0.0015,0.8375,2.2,Excellent,0.001436
4,Kepler-10 b,2025-01-02,1.000316,No,0.0000,0.8375,2.2,Good,-0.000316
5,Kepler-10 b,2025-01-02,1.000153,No,0.0000,0.8375,2.2,Good,-0.000153
6,Kepler-10 b,2025-01-02,0.998384,Yes,0.0015,0.8375,2.2,Good,0.001616
7,Kepler-10 b,2025-01-02,0.999895,No,0.0000,0.8375,2.2,Good,0.000105
8,Kepler-10 b,2025-01-03,1.000048,No,0.0000,0.8375,2.2,Fair,-0.000048
9,Kepler-10 b,2025-01-03,0.998117,Yes,0.0015,0.8375,2.2,Good,0.001883
10,Kepler-10 b,2025-01-03,1.000163,No,0.0000,0.8375,2.2,Good,-0.000163
11,Kepler-10 b,2025-01-04,0.999695,No,0.0000,0.8375,2.2,Fair,0.000305
12,Kepler-10 b,2025-01-04,0.998318,Yes,0.0015,0.8375,2.2,Good,0.001682
13,Kepler-10 b,2025-01-04,0.999718,No,0.0000,0.8375,2.2,Good,0.000282
14,Kepler-10 b,2025-01-04,0.999874,No,0.0000,0.8375,2.2,Excellent,0.000126

In [33]:
print("Low Brightness Observations")
print("Count:", len(low_brightness))

Low Brightness Observations
Count: 0